/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ServerTest_MyThread */

#ifndef _Included_ServerTest_MyThread
#define _Included_ServerTest_MyThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
