/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ServerTest */

#ifndef _Included_ServerTest
#define _Included_ServerTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
